version: '3.8'
services:
  db:
    image: postgres
    restart: 'no'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: investment
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    restart: 'no'
    expose:
      - '${PORT}'
    environment:
      DATABASE_URL: "postgresql://root:root@db:5432/investment?schema=public"
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_EMAIL_SENDER: ${SENDGRID_EMAIL_SENDER}
    container_name: investment-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app
    command: yarn start:local
    depends_on:
      - db

volumes:
  db_data:
