version: '3.8'
services:
  db:
    image: postgres
    restart: 'no'
    expose:
      - '5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: investment
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
